name: riot_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.0.7
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^8.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/skull.svg
    - assets/icons/titleIcon.svg

  fonts:
    - family: NuevaFuente
      fonts:
        - asset: assets/fonts/Arbutus-Regular.ttf
